name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Get System information
        uses: actions/system-info@v1
      - name: Get hardware specifications
        run: |
          echo "CPU: $(uname -m)"
          echo "CPU cores: $(nproc)"
          echo "Memory: $(free -m | awk '/^Mem:/ {print $2}')"
          echo "Disk space: $(df -h | awk '/^Filesystem/ {print $2}')"
      - name: Get OS details
        run: |
          echo "OS: $(cat /etc/os-release | grep ^NAME | cut -d'=' -f2)"
          echo "OS version: $(cat /etc/os-release | grep ^VERSION_ID | cut -d'=' -f2)"
